require("dotenv").config();

const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const Razorpay = require("razorpay");
const crypto = require("crypto");

const app = express();
app.use(express.json());
app.use(cors());

// =======================
// 🔥 CONNECT DB
// =======================

mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
    useUnifiedTopology: true
    })
    .then(()=>console.log("DB CONNECTED"))
    .catch(err=>console.log(err));

    // =======================
    // 🔥 MODELS
    // =======================

    const User = mongoose.model("User", new mongoose.Schema({
      name: String,
        email: String,
          password: String,
            ff_uid: String,
              wallet: { type: Number, default: 0 },
                matches: Array
                }));

                const Match = mongoose.model("Match", new mongoose.Schema({
                  match_name: String,
                    type: String,
                      time: String,
                        entry_fee: Number,
                          max_players: Number,
                            players: Array,
                              room_id: String,
                                password: String,
                                  status: String
                                  }));

                                  // =======================
                                  // 🔴 RAZORPAY
                                  // =======================

                                  const razorpay = new Razorpay({
                                    key_id: process.env.RAZORPAY_KEY,
                                      key_secret: process.env.RAZORPAY_SECRET
                                      });

                                      // =======================
                                      // 🔐 AUTH MIDDLEWARE
                                      // =======================

                                      function auth(req, res, next) {

                                        const token = req.headers["auth"];

                                          if (!token) {
                                              return res.json({ status: "failed", message: "No token" });
                                                }

                                                  try {
                                                      const decoded = jwt.verify(token, process.env.JWT_SECRET);
                                                          req.user = decoded;
                                                              next();
                                                                } catch {
                                                                    res.json({ status: "failed", message: "Invalid token" });
                                                                      }
                                                                      }

                                                                      // =======================
                                                                      // 🔥 REGISTER
                                                                      // =======================

                                                                      app.post("/register", async (req, res) => {

                                                                        try {

                                                                            const { name, email, password } = req.body;

                                                                                const exist = await User.findOne({ email });

                                                                                    if (exist) {
                                                                                          return res.json({ status: "failed", message: "User exists" });
                                                                                              }

                                                                                                  const hash = await bcrypt.hash(password, 10);

                                                                                                      const user = new User({
                                                                                                            name,
                                                                                                                  email,
                                                                                                                        password: hash,
                                                                                                                              wallet: 0,
                                                                                                                                    matches: []
                                                                                                                                        });

                                                                                                                                            await user.save();

                                                                                                                                                res.json({ status: "success", message: "Registered" });

                                                                                                                                                  } catch {
                                                                                                                                                      res.json({ status: "failed", message: "Error" });
                                                                                                                                                        }
                                                                                                                                                        });

                                                                                                                                                        // =======================
                                                                                                                                                        // 🔥 LOGIN
                                                                                                                                                        // =======================

                                                                                                                                                        app.post("/login", async (req, res) => {

                                                                                                                                                          try {

                                                                                                                                                              const { email, password } = req.body;

                                                                                                                                                                  const user = await User.findOne({ email });

                                                                                                                                                                      if (!user) {
                                                                                                                                                                            return res.json({ status: "failed", message: "User not found" });
                                                                                                                                                                                }

                                                                                                                                                                                    const ok = await bcrypt.compare(password, user.password);

                                                                                                                                                                                        if (!ok) {
                                                                                                                                                                                              return res.json({ status: "failed", message: "Wrong password" });
                                                                                                                                                                                                  }

                                                                                                                                                                                                      const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET);

                                                                                                                                                                                                          res.json({
                                                                                                                                                                                                                status: "success",
                                                                                                                                                                                                                      token: token,
                                                                                                                                                                                                                            user_id: user._id,
                                                                                                                                                                                                                                  wallet: user.wallet
                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                            res.json({ status: "failed", message: "Login error" });
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                              // =======================
                                                                                                                                                                                                                                              // 🔥 GET MATCHES
                                                                                                                                                                                                                                              // =======================

                                                                                                                                                                                                                                              app.get("/get-matches", async (req, res) => {

                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                    const matches = await Match.find();
                                                                                                                                                                                                                                                        res.json({ status: "success", data: matches });
                                                                                                                                                                                                                                                          } catch {
                                                                                                                                                                                                                                                              res.json({ status: "failed", message: "Error" });
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                // =======================
                                                                                                                                                                                                                                                                // 🔥 JOIN MATCH
                                                                                                                                                                                                                                                                // =======================

                                                                                                                                                                                                                                                                app.post("/join-match", auth, async (req, res) => {

                                                                                                                                                                                                                                                                  try {

                                                                                                                                                                                                                                                                      const { match_id, ff_uid } = req.body;

                                                                                                                                                                                                                                                                          const user = await User.findById(req.user.id);
                                                                                                                                                                                                                                                                              const match = await Match.findById(match_id);

                                                                                                                                                                                                                                                                                  if (!user || !match) {
                                                                                                                                                                                                                                                                                        return res.json({ status: "failed", message: "Invalid" });
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                if (match.status !== "upcoming") {
                                                                                                                                                                                                                                                                                                      return res.json({ status: "failed", message: "Match not joinable" });
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                              if (match.players.length >= match.max_players) {
                                                                                                                                                                                                                                                                                                                    return res.json({ status: "failed", message: "Match full" });
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                            const already = match.players.find(p => p.user_id == user._id);

                                                                                                                                                                                                                                                                                                                                if (already) {
                                                                                                                                                                                                                                                                                                                                      return res.json({
                                                                                                                                                                                                                                                                                                                                              status: "success",
                                                                                                                                                                                                                                                                                                                                                      message: "Already joined",
                                                                                                                                                                                                                                                                                                                                                              room_id: match.room_id,
                                                                                                                                                                                                                                                                                                                                                                      password: match.password,
                                                                                                                                                                                                                                                                                                                                                                              wallet: user.wallet
                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                            if (user.wallet < match.entry_fee) {
                                                                                                                                                                                                                                                                                                                                                                                                  return res.json({ status: "failed", message: "Low balance" });
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                          user.wallet -= match.entry_fee;

                                                                                                                                                                                                                                                                                                                                                                                                              match.players.push({
                                                                                                                                                                                                                                                                                                                                                                                                                    user_id: user._id,
                                                                                                                                                                                                                                                                                                                                                                                                                          ff_uid: ff_uid
                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                  user.matches.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                        match_id: match._id,
                                                                                                                                                                                                                                                                                                                                                                                                                                              room_id: match.room_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    password: match.password
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                            await user.save();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                await match.save();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          status: "success",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: "Joined",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      room_id: match.room_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            password: match.password,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  wallet: user.wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ status: "failed", message: "Join error" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // =======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 🔥 WALLET
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // =======================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.get("/wallet", auth, async (req, res) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const user = await User.findById(req.user.id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: "success",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          wallet: user.wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 🔥 PAYMENT LINK
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =======================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.post("/create-payment-link", auth, async (req, res) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { amount } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const link = await razorpay.paymentLink.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            amount: amount * 100,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currency: "INR",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        description: "Wallet Deposit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              notes: { user_id: req.user.id }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.json({ status: "success", link: link.short_url });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ status: "failed", message: "Payment error" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // =======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 🔥 WEBHOOK
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // =======================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.post("/razorpay-webhook", (req, res) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const shasum = crypto.createHmac("sha256", process.env.WEBHOOK_SECRET);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  shasum.update(JSON.stringify(req.body));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const digest = shasum.digest("hex");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (digest !== req.headers["x-razorpay-signature"]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(400).send("Invalid signature");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (req.body.event === "payment_link.paid") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const data = req.body.payload.payment_link.entity;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const amount = data.amount_paid / 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const user_id = data.notes.user_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              User.findById(user_id).then(user => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            user.wallet += amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user.save();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.json({ status: "ok" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // =======================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 🚀 START SERVER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // =======================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  app.listen(process.env.PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log("SERVER RUNNING ON PORT " + process.env.PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });require